package WebService::Async::Desk::Base::Attachment;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Attachment - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 file_name

name of the file.

=cut

sub file_name : method { shift->{file_name} }

=head2 content_type

file's content type, e.g. image/png.

=cut

sub content_type : method { shift->{content_type} }

=head2 size

file size.

=cut

sub size : method { shift->{size} }

=head2 url

url to get the file; see Attachment URLs.

=cut

sub url : method { shift->{url} }

=head2 erased_at

when the attachment was erased; see Delete Attachment.

=cut

sub erased_at : method { shift->{erased_at} }

=head2 created_at

when the attachment was created.

=cut

sub created_at : method { shift->{created_at} }

=head2 updated_at

when the attachment was last updated.

=cut

sub updated_at : method { shift->{updated_at} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

