package WebService::Async::Desk::Base::Case;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Case - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 id

integer identifier for this object.

=cut

sub id : method { shift->{id} }

=head2 external_id

unique external identifier to reference this case to an external system.

=cut

sub external_id : method { shift->{external_id} }

=head2 blurb

short summary of, or excerpt from, the case.

=cut

sub blurb : method { shift->{blurb} }

=head2 subject

subject of the case.

=cut

sub subject : method { shift->{subject} }

=head2 priority

number between 1 and 10, 1 being lowest priority.

=cut

sub priority : method { shift->{priority} }

=head2 description

description or background information.

=cut

sub description : method { shift->{description} }

=head2 status

current state of the case, one of: new, open, pending, resolved, closed, deleted.

=cut

sub status : method { shift->{status} }

=head2 type

channel of the case, one of: chat, twitter, email, qna, facebook, phone.

=cut

sub type : method { shift->{type} }

=head2 labels

array of labels associated with this case.

=cut

sub labels : method { shift->{labels} }

=head2 label_ids

array of label ids associated with this case.

=cut

sub label_ids : method { shift->{label_ids} }

=head2 language

the case's ISO language code, which returns the site's default language (or nil if not set) unless multi-lingual support is enabled.

=cut

sub language : method { shift->{language} }

=head2 custom_fields

hash of values for custom fields.

=cut

sub custom_fields : method { shift->{custom_fields} }

=head2 created_at

when this record was created.

=cut

sub created_at : method { shift->{created_at} }

=head2 updated_at

when this record was last updated by any action.

=cut

sub updated_at : method { shift->{updated_at} }

=head2 changed_at

when this case was last updated by a user.

=cut

sub changed_at : method { shift->{changed_at} }

=head2 active_at

when this case was last active.

=cut

sub active_at : method { shift->{active_at} }

=head2 received_at

when the most recent message was received.

=cut

sub received_at : method { shift->{received_at} }

=head2 locked_until

when the lock on this case will expire.

=cut

sub locked_until : method { shift->{locked_until} }

=head2 first_opened_at

when this case was first opened.

=cut

sub first_opened_at : method { shift->{first_opened_at} }

=head2 opened_at

when this case was most recently opened.

=cut

sub opened_at : method { shift->{opened_at} }

=head2 first_resolved_at

when this case was first resolved.

=cut

sub first_resolved_at : method { shift->{first_resolved_at} }

=head2 resolved_at

when this case was most recently resolved.

=cut

sub resolved_at : method { shift->{resolved_at} }

=head2 suppress_rules

set to true to disable rule processing when creating or updating this case.

=cut

sub suppress_rules : method { shift->{suppress_rules} }

=head2 route_status

current routing status of the case. this field only appears when routing is enabled for the first time. there are four values: added when a case is first added to desk. this switches to available after a few seconds.available case is not in use and can be routed. assigned case is being presented to a specific user to accept. active a case is open and in edit mode. doesn't necessarily have to have been routed..

=cut

sub route_status : method { shift->{route_status} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

