package WebService::Async::Desk::Base::Customer;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Customer - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 id

string identifier for this object.

=cut

sub id : method { shift->{id} }

=head2 first_name

customer's first name.

=cut

sub first_name : method { shift->{first_name} }

=head2 last_name

customer's last name.

=cut

sub last_name : method { shift->{last_name} }

=head2 company

customer's company.

=cut

sub company : method { shift->{company} }

=head2 title

customer's title.

=cut

sub title : method { shift->{title} }

=head2 avatar

customer's avatar URL - image sourced from Twitter, Facebook or Gravatar. See note on avatar_size param below..

=cut

sub avatar : method { shift->{avatar} }

=head2 uid

customer's Multipass SSO UID.

=cut

sub uid : method { shift->{uid} }

=head2 external_id

unique external identifier to reference this customer to an external system.

=cut

sub external_id : method { shift->{external_id} }

=head2 background

any background information for the customer.

=cut

sub background : method { shift->{background} }

=head2 language

customer's ISO language code, nil unless multi-lingual support is enabled.

=cut

sub language : method { shift->{language} }

=head2 locked_until

time in which the lock on this customer will expire.

=cut

sub locked_until : method { shift->{locked_until} }

=head2 created_at

time when customer was created.

=cut

sub created_at : method { shift->{created_at} }

=head2 updated_at

time when customer was last updated at.

=cut

sub updated_at : method { shift->{updated_at} }

=head2 emails

array of email objects, each specifying the contact type and value of the email address.

=cut

sub emails : method { shift->{emails} }

=head2 phone_numbers

array of phone number objects, each specifying the contact type and value of the phone number.

=cut

sub phone_numbers : method { shift->{phone_numbers} }

=head2 addresses

array of address objects, each specifying the contact type and value of the location.

=cut

sub addresses : method { shift->{addresses} }

=head2 custom_fields

hash of values for custom fields.

=cut

sub custom_fields : method { shift->{custom_fields} }

=head2 access_private_portal

whether or not customer can access private portal.

=cut

sub access_private_portal : method { shift->{access_private_portal} }

=head2 access_company_cases

whether or not customer can access company cases.

=cut

sub access_company_cases : method { shift->{access_company_cases} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

