package WebService::Async::Desk::Base::CustomField;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::CustomField - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 name

custom field name. This corresponds with the key value in the Desk.com Admin.

=cut

sub name : method { shift->{name} }

=head2 label

custom field label. This corresponds with the name value in the Desk.com Admin.

=cut

sub label : method { shift->{label} }

=head2 type

'ticket' or 'customer' or 'company'.

=cut

sub type : method { shift->{type} }

=head2 active

whether or not this custom field is active.

=cut

sub active : method { shift->{active} }

=head2 data

a hash containing the custom field's data type ('string', 'boolean', 'integer', 'date' or 'list'); if the custom field is a list, this field will also contain an array of choices.

=cut

sub data : method { shift->{data} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

