package WebService::Async::Desk::Base::Job;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Job - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 type

the type of job. Options include bulk_case_update or customer_merge.

=cut

sub type : method { shift->{type} }

=head2 status_message

a descriptive message of the job's status.

=cut

sub status_message : method { shift->{status_message} }

=head2 progress

percent complete.

=cut

sub progress : method { shift->{progress} }

=head2 created_at

when the job was created.

=cut

sub created_at : method { shift->{created_at} }

=head2 completed_at

when the job was finished.

=cut

sub completed_at : method { shift->{completed_at} }

=head2 last_error

any errors encountered while finishing the job. null if job completes successfully..

=cut

sub last_error : method { shift->{last_error} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

