package WebService::Async::Desk::Base::Label;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Label - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 id

identifier for this resource.

=cut

sub id : method { shift->{id} }

=head2 name

name of the label.

=cut

sub name : method { shift->{name} }

=head2 description

an optional description.

=cut

sub description : method { shift->{description} }

=head2 enabled

whether or not the label can be used in the Agent.

=cut

sub enabled : method { shift->{enabled} }

=head2 types

an array of the label's types. Can be case or macro.

=cut

sub types : method { shift->{types} }

=head2 color

the color representing the label - one of default, blue, white, yellow, red, orange, green, black, purple, brown, grey, pink.

=cut

sub color : method { shift->{color} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

