package WebService::Async::Desk::Base::Note;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Note - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 body

Message body..

=cut

sub body : method { shift->{body} }

=head2 created_at

Time of creation..

=cut

sub created_at : method { shift->{created_at} }

=head2 updated_at

Time last updated..

=cut

sub updated_at : method { shift->{updated_at} }

=head2 erased_at

Time at which an agent erased this note..

=cut

sub erased_at : method { shift->{erased_at} }

=head2 suppress_rules

set to true to disable rule processing when creating or updating this note.

=cut

sub suppress_rules : method { shift->{suppress_rules} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

