package WebService::Async::Desk::Base::Reply;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Reply - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 direction

Direction of the reply, in for coming into the agent or out for sending out of the agent..

=cut

sub direction : method { shift->{direction} }

=head2 body

Body of the reply..

=cut

sub body : method { shift->{body} }

=head2 created_at

time of creation.

=cut

sub created_at : method { shift->{created_at} }

=head2 updated_at

time last updated.

=cut

sub updated_at : method { shift->{updated_at} }

=head2 sent_at

time an outbound reply was sent. nil for inbound replies and all chat replies..

=cut

sub sent_at : method { shift->{sent_at} }

=head2 suppress_rules

set to true to disable rule processing when creating or updating this reply.

=cut

sub suppress_rules : method { shift->{suppress_rules} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

