package WebService::Async::Desk::Base::Snippet;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::Snippet - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 name

The name (and primary key) of the snippet.

=cut

sub name : method { shift->{name} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

