package WebService::Async::Desk::Base::SystemMessage;

use strict;
use warnings;

# VERSION

=head1 NAME

WebService::Async::Desk::Base::SystemMessage - support for desk.com entity

=head1 DESCRIPTION

This is autogenerated from the L<https://www.desk.com> API documentation.

=cut

=head1 METHODS - Attributes

=head2 message

the body of the system message.

=cut

sub message : method { shift->{message} }

=head2 updated_at

time when system message was updated.

=cut

sub updated_at : method { shift->{updated_at} }

1;

__END__

=head1 AUTHOR

binary.com C<< BINARY@cpan.org >>

=head1 LICENSE

Copyright binary.com 2017-2019. Licensed under the same terms as Perl itself.

